//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FifthLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialStatements
    {
        public int Financial_ID { get; set; }
        public Nullable<int> Employee_ID { get; set; }
        public int Quantity { get; set; }
        public decimal Revenue { get; set; }
        public Nullable<int> Sale_ID { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Sales Sales { get; set; }
    }
}
