//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FifthLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogPass
    {
        public int Log_ID { get; set; }
        public string LoginIN { get; set; }
        public string PasswordIN { get; set; }
        public Nullable<int> Role_ID { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
