//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FifthLab
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CircusEntities : DbContext
    {
        public CircusEntities()
            : base("name=CircusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Discounts> Discounts { get; set; }
        public virtual DbSet<EmloyeeWorkSchedule> EmloyeeWorkSchedule { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<FinancialStatements> FinancialStatements { get; set; }
        public virtual DbSet<LogPass> LogPass { get; set; }
        public virtual DbSet<PaymentTypes> PaymentTypes { get; set; }
        public virtual DbSet<Perfomances> Perfomances { get; set; }
        public virtual DbSet<Reserves> Reserves { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Sales> Sales { get; set; }
        public virtual DbSet<Tickets> Tickets { get; set; }
        public virtual DbSet<TypesOfBenefits> TypesOfBenefits { get; set; }
    }
}
