//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FifthLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserves
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reserves()
        {
            this.Sales = new HashSet<Sales>();
        }
    
        public int Reserve_ID { get; set; }
        public Nullable<int> Ticket_ID { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public System.DateTime ReserveDate { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Tickets Tickets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales> Sales { get; set; }
    }
}
