//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FifthLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserves
    {
        public int Reserve_ID { get; set; }
        public Nullable<int> Ticket_ID { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public System.DateTime ReserveDate { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Tickets Tickets { get; set; }
    }
}
