//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FifthLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sales()
        {
            this.FinancialStatements = new HashSet<FinancialStatements>();
        }
    
        public int Sale_ID { get; set; }
        public Nullable<int> Employee_ID { get; set; }
        public Nullable<int> Reserve_ID { get; set; }
        public System.DateTime SaleDate { get; set; }
        public Nullable<int> Discount_ID { get; set; }
        public Nullable<int> Payment_ID { get; set; }
        public decimal Amount { get; set; }
    
        public virtual Discounts Discounts { get; set; }
        public virtual Employees Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinancialStatements> FinancialStatements { get; set; }
        public virtual PaymentTypes PaymentTypes { get; set; }
        public virtual Reserves Reserves { get; set; }
    }
}
